### ISSUE TITLE
Cursor moves to end of input field during validation

### ISSUE THREAD

**Issue by jsancho** [dpoetzsch/md-pickers#20] opened 2017-07-13 16:47 UTC
Steps to reproduce

- Create a date or time picker with `mdp-open-on-click ="false` so that you can edit by typing
- Type a value with valid formatting, e.g. `07-10-2017`
- delete any character (other than the last one) so that the input is invalidated 
- the cursor will automatically move to the last position.

Essentially, say that someone has chosen the wrong month and wants to edit the value.
It is awkward to edit, because as soon as a character is changed, the cursor will jump to the end

Here's an example with the current version of the code in the demo page
![mdpickers_bug](https://user-images.githubusercontent.com/1547884/28177613-49b508c8-67f3-11e7-96cb-a2fea9a3ef57.gif)

thanks for looking at this guys :)

ps: I would be happy to give it a shot myself and submit a PR.
However, my angular skills are a bit rusty. If you could give me a bit of guidance and what to look for, or anything particular that you are using that deviates from standard angular form validation.

thanks again

**Comment by dpoetzsch** [comment] 2017-07-14 15:46
Hi @jsancho, thanks for reporting the issue.

Your want to look at the `mdpDatePicker` directive. Probably this has something to do with the formatter updating the model value after every input even if it is the same value.

**Comment by dpoetzsch** [comment] 2017-07-14 16:00
I just tried this with firefox in the demo file delivered with this package.

I changed line 44 in `demo/app.js` to

`$mdpLocale.date.openOnClick = false;`.

Started the local server and I was easily able to enter and correct input:

![peek 2017-07-14 17-58](https://user-images.githubusercontent.com/7511464/28220043-56a3c51c-68be-11e7-9c85-69e0e9bea9d4.gif)

**Comment by dpoetzsch** [comment] 2017-07-14 16:58
Update: I can reproduce the behavior in chrome

**Comment by jsancho** [comment] 2017-07-14 17:08
Oh I see, it could be a Chrome thing - I should have mentioned that.
For the record, I think the issue happens in the same way with the time picker.
thanks

**Comment by robin-thoni** [comment] 2017-07-14 21:46
I saw the same behavior when I was playing with intl-phone-number: the cursor is moved to the end when the model and/or (i don't remember) view value changes. The trick was to save then reset the cursor position when needed

**Comment by dpoetzsch** [comment] 2017-08-01 16:28
So this is quite funny. I tried to reproduce the behavior in chrome to check your PR @MincedCutlet (thanks for that btw) but I could not reproduce it any more.

My specs:

Fedora 25
Browsers: Chrome 60.0.3112.78 & Firefox 54.0.

Maybe the new chrome version fixed the bug? What do your browsers say?

**Comment by MincedCutlet** [comment] 2017-08-01 16:36
OS: Mac Yosemite
Browser: Chrome: 59.0.3071.115 was able to reproduce the issue. 
Noticed there was an update, and after upgrading to 60.0.3112.78 noticed the issue was resolved.

Seems like it is resolved.

**Comment by jsancho** [comment] 2017-08-02 13:08
I can confirm that by upgrading from Chrome 59.0.3071.115 to Chrome 60.0.3112.78 this issue has been resolved.
Amazing work @MincedCutlet not only in providing a fix, but also in noticing the Chrome update. 👍

**Comment by dpoetzsch** [comment] 2017-08-02 15:35
Alright, I'll close this then. Thanks for your input :)

**Closed as completed by dpoetzsch** 2017-08-02 15:35 UTC
Labels: bug

**Comment by dpoetzsch** [comment] 2017-08-02 15:36
Ok, I'll close this then. Thanks for your input :)
